### ISSUE TITLE
some trouble in debug

### ISSUE THREAD

**Issue by lyhh123** [odegeasslbc/Self-Supervised-Sketch-to-Image-Synthesis-PyTorch#3]
Hello, There are some matters when I try to train the Sketch-to-image model with your code.
At line 22 of the file "train_step_2_gan.py", I couldn't find the file "generate_matrix".I found the function with the same name in the other two files in the folder "evaluate". I don't know which is the right.

**Comment by bingchenlll** [comment]
Hi

you can use this one:
https://github.com/odegeasslbc/Self-Supervised-Sketch-to-Image-Synthesis-PyTorch/blob/356d33ee6457e2db251b9d6fd1527340663f5a4b/evaluate/generate_image_matrix.py#L8

Basically, it is just a script to generate the samples during training so we can monitor how the model performs. You can customize and write your own "generate_matrix" function and save the results in the way you like.

**Comment by lyhh123** [comment]
> 
> 
> Hi
> 
> you can use this one:
> 
> https://github.com/odegeasslbc/Self-Supervised-Sketch-to-Image-Synthesis-PyTorch/blob/356d33ee6457e2db251b9d6fd1527340663f5a4b/evaluate/generate_image_matrix.py#L8
> 
> Basically, it is just a script to generate the samples during training so we can monitor how the model performs. You can customize and write your own "generate_matrix" function and save the results in the way you like.

I got it!Thanks for your help.
