### ISSUE TITLE
12000.pth

### ISSUE THREAD

**Issue by CatDogS** [odegeasslbc/Self-Supervised-Sketch-to-Image-Synthesis-PyTorch#5]
hi, i make an error : `[Errno 2] No such file or directory: 'pretrained/models/12000.pth'`

where should i find it?

 `PRETRAINED_AE_ITER = 12000`  in  `config.py`

**Comment by CatDogS** [comment]
thank you

**Comment by xiaoting-hub** [comment]
same question here.  @odegeasslbc

**Comment by wangqiang9** [comment]
> hi, i make an error : `[Errno 2] No such file or directory: 'pretrained/models/12000.pth'`
> 
> where should i find it?
> 
> `PRETRAINED_AE_ITER = 12000` in `config.py`

in config.py, change `PRETRAINED_AE_PATH=None`
